### ISSUE TITLE
Add hover text on map

### ISSUE THREAD

**Issue by thedivtagguy** [thedivtagguy/datajam-elections#5]
Literally the most requested enhancement.

**Comment by thedivtagguy** [comment]
Will be solved by #1 when it is resolved

**Comment by SikandarJODD** [comment]
[Layerchat Geo Path](https://www.layerchart.com/docs/examples/GeoPath) might solve this problem if this includes layerchart

**Comment by thedivtagguy** [comment]
Hey @SikandarJODD 
Yep it would! I've been slow at moving on this but I believe @Vonter is porting the map to a Maplibre variant which would automatically solve our text issues. 

In the meantime, you want to take a stab at handling hover text in the current map feel free to open a PR :)

**Comment by thedivtagguy** [comment]
PR #14 has added this but could do with better sized text when the user is zoomed out.
